### ISSUE TITLE
Couldn't find a valid ICU package installed on the system

### ISSUE THREAD

**Issue by diblasio** [mikedickey/RoonServer#2]
Currently I'm forced to upgrade Roon from 1.7 to 1.8 to be able to connect with any app. If I click upgrade and then relaunch the process exits with the following message:

```
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_CurrentUICulture()
   at System.TimeZoneInfo..ctor(Byte[], System.String, Boolean)
   at System.TimeZoneInfo.GetTimeZoneFromTzData(Byte[], System.String)
   at System.TimeZoneInfo.GetLocalTimeZoneFromTzFile()
   at System.TimeZoneInfo+CachedData.CreateLocal()
   at System.DateTime.get_Now()
   at Base.Utils..cctor()
   at Base.Utils.SetApplicationName(System.String, System.String)
   at Sooloos.App.Main(System.String[])
/opt/RoonServer/start.sh: line 52:   123 Aborted                 (core dumped) "$P" "$@"
/opt/RoonServer/start.sh: line 34: kill: (123) - No such process
```

**Comment by diblasio** [comment]
looks like adding the following env will work around the problem:

```
DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
```

Found from https://stackoverflow.com/a/64370938

**Comment by dannydulai** [comment]
I suggest you install icu. That env car could lead to inconsistencies.
